name: Java 21 CI with Gradle (Main & Dev)

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - 'backend/back/src/**'
      - 'backend/back/build.gradle*'
      - 'Dockerfile'
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'backend/back/src/**'
      - 'backend/back/build.gradle*'
      - 'Dockerfile'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # 커밋이 짧은 시간안에 몰려도 최신 커밋에 대해서만 액션이 수행되도록
  cancel-in-progress: false # 기존에 시작된 작업은 새 커밋이 들어왔다고 해서 바로 끄지 않고 끝날때까지 대기
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2 # 또는 oss 버전
        ports:
          - 9200:9200
        env:
          discovery.type: single-node
          xpack.security.enabled: "false"
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
          

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-root-directory: ./backend/back
          cache-encryption-key: "force-refresh-v2"
          cache-disabled: false

      - name: Wait for Elasticsearch to be ready
        run: |
          for i in {1..60}; do
            if curl -s http://localhost:9200/_cluster/health | grep -q 'status'; then
            echo "Elasticsearch is ready!"
            exit 0
            fi
            echo "Waiting for ES... ($i/60)"
            sleep 1 # 1초마다 체크해서 준비되자마자 바로 다음 단계로!
          done
          exit 1

      - name: Test with Gradle6
        if: >
          !contains(github.head_ref || github.ref, 'hotfix') &&
          !contains(github.event.head_commit.message, 'hotfix')
        run: ./gradlew test --build-cache
        working-directory: ./backend/back
        env:
          SPRING_CACHE_TYPE: none
          SPRING_APPLICATION_JSON: >
            {
              "custom": {
                "jwt": {
                  "secretKey": "${{ secrets.CUSTOM_JWT_SECRET_KEY }}"
                }
              }
            }
          SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb;MODE=MySQL
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
          SPRING_DATASOURCE_USERNAME: sa
          SPRING_DATASOURCE_PASSWORD: ""
          CUSTOM_API_ESTATE_KEY: ${{secrets.CUSTOM_API_ESTATE_KEY}}
          CUSTOM_API_ESTATE_URL: ${{secrets.CUSTOM_API_ESTATE_URL}}
          CUSTOM_API_GEO_URL: ${{ secrets.CUSTOM_API_GEO_URL }}
          CUSTOM_API_GEO_KEY: ${{ secrets.CUSTOM_API_GEO_KEY }}
          SPRING_DATA_REDIS_HOST: localhost
          SPRING_DATA_REDIS_PORT: 6379
          CUSTOM_ELASTICSEARCH_HOST: localhost
          CUSTOM_ELASTICSEARCH_PORT: 9200
          CUSTOM_ELASTICSEARCH_SCHEME: http
  call-cd-workflow:
    needs: build-and-test # ci-build Job이 성공해야만 실행됨
    # 조건: push 이벤트이면서 main 브랜치일 때만 무중단 배포 워크플로우 호출
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml # 파일 경로에 맞게 지정
